ccnmtl/django-pagetree

pagetree/generic/views.py
Add a check in the pagetree section's gate_check() method to check for a
valid user. Going through this code as an anonymous user (as
demonstrated in `PageTreeViewTestsLoggedOut` of `ccnmtldjango`) currently
causes this error:
TypeError at /pages/session-1/
int() argument must be a string or a number, not 'SimpleLazyObject'
Note that there is an existing user presence check in `pagetree.models.Section.gate_check()`. When first trying to fix this error, I added the `is_anonymous()` check there, but it caused a redirect loop. Instead I've put this in the `Section` view. The check in the `Section` model may no longer be necessary, but I'm not very familiar with this code yet - I'm not sure.
=> Fix TypeError when accessing a gated page as an anonymous user

pagetree/templates/pagetree/edit_page.html, pagetree/templates/pagetree/page.html, pagetree/templates/pagetree/test_page.html
I did this same thing on quizblock, but it turns out the template I'm
running into a "CSRF Failed" error on is actually in pagetree.
=> Add CSRF token to all post forms

pagetree/generic/views.py
Commit c4d83cfd9b8cae89083e455211b7f3e9d11bf660 updated these generic
views to class-based views, but the examples in the documentation still
used function-based views, which no longer works.
=> Update generic view docs examples

pagetree/templates/pagetree/edit_page.html
The large 'delete' button was making me nervous - I think only the trash
can icon is necessary, with the "Delete" text in the title attribute.
I also separated the export button so the edit and delete buttons have
the correct border.
=> Small UI improvements in the block editor

pagetree/models.py
This method is required in order for pageblocks to be created
via a dictionary - i.e. for testing purposes.
See comment here:
https://github.com/ccnmtl/worth2/pull/45#issuecomment-74080916
=> Add PageBlock.create_from_dict method

pagetree/generic/views.py
I was specifying the wrong arguments in my original example.
=> Fix get_extra_context override in PageView example

pagetree/templates/pagetree/edit_page.html
Jess pointed out that the section navigation is already in the "Hierarchy"
tab of the edit page, and there's no reason to show it twice.
=> Remove superfluous nav menu from edit section - PMT #99383

runtests.py, test_reqs.txt
Pagetree was only getting tested with Django 1.6, since the version
specified in test_reqs.txt is 1.6. The solution is to remove Django from test_reqs and
use the version in `.travis.yml`.
=> Fix for testing pagetree on multiple django versions

pagetree/models.py, pagetree/tests/test_models.py
It's convenient to define custom pageblocks' create_from_dict method
as passing in the complete dictionary as kwargs on creation. e.g.:
```python
@classmethod
def create_from_dict(cls, d):
return cls.objects.create(**d)
```
In order for this to work, the basic keys that the dictionary
will contain: `block_type`, `label`, and `css_extra` need to be
removed before calling the custom pageblock's create_from_dict hook.
=> Remove unnecessary params when calling create_from_dict

CHANGES.txt, pagetree/models.py, pagetree/tests/test_models.py, pagetree/tests/test_views.py, pagetree/views.py, setup.py
Allow extra_css and label to be exported from PageBlock, as well as the content object's attributes
* enable block level import_from_dict/as_dict that cascades to the content object import_from_dict/as_dict
=> PageBlock as_dict/import_from_dict cascade

pagetree/__init__.py, pagetree/generic/models.py, pagetree/models.py, pagetree/test_models.py, pagetree/tests/factories.py
I moved TestBlock outside models.py mainly so I could inherit BasePageBlock
from it, so that code gets tested. I think it makes more sense to have the
TestBlock in a different file than the actual pagetree models anyways.
=> Add BasePageBlock and move TestBlock to test_models.py

docs/conf.py
Sphinx 1.2.2 that's on readthedocs.org doesn't allow the conf's
source_suffix to be a list. I created the conf with Sphinx 1.3.
This change will hopefully fix the build error here:
https://readthedocs.org/builds/django-pagetree/2432598/
/site-packages/sphinx/util/__init__.py", line 94, in get_matching_docs
suffixpattern = '*' + suffix
TypeError: cannot concatenate 'str' and 'list' objects
=> Fix sphinx conf for readthedocs.org

pagetree/models.py
This is similar to what I did for the Add PageBlock form here: 873fd748
=> Prevent duplicate id attributes in edit form

docs/conf.py
The default 'alabaster' theme isn't in sphinx 1.2.2 on readthedocs.org:
https://readthedocs.org/builds/django-pagetree/2449340/
=> Use 'default' theme for readthedocs.org compatibility

pagetree/templates/pagetree/edit_page.html
I added bold text and an extra icon here to make it clearer where you
are in the hierarchy.
=> Make selected hierarchy section more obvious

CHANGES.txt, pagetree/models.py
When debugging the `is_last_child` cache, I saw the value
of cache.get() here is either 1, 0, or None if the cached
value isn't present. Currently, only values of 1 are getting
used, because if the value is 0, the `if v:` to check if
the cache is present fails. I think we need to be more
specific here and do: `if v is not None:`
This change improved performance a little bit in my local testing
with memcached, but it's still not great: Calling the cache for
each node in the tree takes time, and it would be great to find
a way to interact with the cache just once for the pagetree edit
page.
refs #63
=> Fix bug where cached value wasn't used when value was 0

CHANGES.txt, pagetree/templates/pagetree/edit_page.html, setup.py
Sections with empty labels do not display properly in the edit page hierarchy. Provide a custom display.
=> Fix Edit Page Display

pagetree/templates/pagetree/page.html
* I took the edit page link out of the `<li>` tag, since it's not
valid html to have an `<li>` tag outside of a `<ul>` element, and
we don't need it anyways.
* Cleaned up some formatting for the navbar `<ul>`.
=> Markup changes in page.html

pagetree/templates/pagetree/edit_page.html
This class causes bootstrap to render the text as white,
and we're not using it anyways, so I removed it.
=> Remove 'label' class from the pageblock count

pagetree/generic/views.py, pagetree/models.py, pagetree/views.py
Because PageBlock.block() returns a ForeignKey, it results in
a query to the database.
=> Remove duplicate queries when calling PageBlock.block()

pagetree/models.py, pagetree/templates/pagetree/edit_page.html, pagetree/templates/pagetree/page.html, pagetree/templates/pagetree/test_page.html, pagetree/templates/pagetree/testblock.html
Because 'block' has the potential to conflict with django's 'block'
templatetag.
Closes github issue #29
=> Use 'pageblock' instead of 'block' as django template var

requirements.txt
The documentation build has been failing with the error:
ImportError: No module named django.conf
because django isn't installed when the documentation is built,
and I have 'autodoc' enabled to automatically read in the documentation
from the code.
https://readthedocs.org/projects/django-pagetree/builds/3236992/
By default, readthedocs uses `requirements.txt` to install dependencies,
so this should fix the error.
=> Add requirements.txt to fix readthedocs build

README.md
This is no longer relevant since django 1.7 and south aren't supported anymore
=> Remove notes on django 1.7 / south

.travis.yml
This option was removed in pip 7.0.0 - https://pip.pypa.io/en/stable/news/
=> remove --use-mirrors

pagetree/templates/pagetree/clone_hierarchy.html, pagetree/templates/pagetree/edit_page.html, setup.py
We're using django-bootstrap3 on all our projects that use bootstrap,
so it's simpler to use its form renderer.
=> Switch to django-bootstrap3 form rendering

pagetree/forms.py, pagetree/tests/test_forms.py
=> Add error messaging when user tries to create a duplicate hierarchy

pagetree/forms.py
This allows inheriting forms to also use the clean() method in the documented way, without having to look at self.cleaned_data
=> return cleaned_data when done validating

CHANGES.txt, pagetree/models.py, pagetree/tests/test_models.py
Those fields shouldn't be required anywhere.
=> make label/css_extra not required on add form

CHANGES.txt, pagetree/migrations/0002_delete_testblock.py
At one point in the past, the `TestBlock` model was visible to the
migration system and a bunch of our apps have a stray
`pagetree_testblock` table in the database. When `manage.py migrate` is
run against those databases, we get:
```
Your models have changes that are not yet reflected in a migration, and so won't be applied.
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```
Running `manage.py makemigrations` will create a pagetree migration that
deletes the table.
Unfortunately, if that gets checked in, it breaks the apps that managed
to avoid getting that `pagetree_testblock` table created in the first
place (it tries to delete a table that doesn't exist and that fails).
Even more importantly, it breaks the unit tests since the …
=> migration to delete TestBlock table if it exists

pagetree/models.py
This otherwise wouldn't get executed - I'm surprised flake8 didn't catch
it.
=> Fix a cache clear after a return statement

docs/configuration.rst, docs/index.rst, pagetree/models.py
I've added some caching to some of UELC's db-intensive functions,
reducing queries on the facilitator page:
https://github.com/ccnmtl/uelc/tree/uelchandler-caching
This requires a hook for custom cache clearing when the tree is changed,
so we don't present the user with outdated data.
This is related to PMT #107228
=> Add custom cache clear option

pagetree/models.py, pagetree/views.py
This PR switches the show_toc and deep_toc fields to render as radio buttons with explicit true/false values. This change resolves two issues:
1. The "required" attribute on the `show_toc` and `deep_toc` checkbox fields was triggering [HTML5 validation rules](https://www.w3.org/WAI/tutorials/forms/validation/#validating-required-input). This validation was preventing users from submitting the form unless these fields were checked. Though these are required database fields, a valid value is False. (Note: adding a "required=False" to the BooleanField would've resolved #1, but not #2.)
2. The checkbox fields were returning "on" as a checked value, as the Bootstrap renderer was not setting the value attribute. The view code is (rightly) expecting a boolean field, and was blowing up.
Switching …
=> Html5 validation

pagetree/forms.py, pagetree/templates/pagetree/clone_hierarchy.html, pagetree/tests/test_forms.py
This will allow me to create a more user-friendly clone form in UELC -
PMT #110243
=> Make base_url an optional argument for cloning

.travis.yml
All apps are off django 1.9: https://pmt.ccnmtl.columbia.edu/milestone/4773/
(mediathread is still on 1.8, and doesn't use pagetree)
=> Remove django 1.9 testing

.travis.yml
The `distributions` option belongs in the `deploy` section: https://docs.travis-ci.com/user/deployment/pypi/#Uploading-different-distributions
Currently only the sdist package is getting deployed: https://pypi.python.org/pypi/django-pagetree/1.3.2
=> fix wheel generation

runtests.py
This was only needed for Django 1.8.
=> Remove MIDDLEWARE_CLASSES in test runner

setup.cfg, setup.py
We build packages as python3-only now, so we don't need to universal setting.
=> Update contact email, remove setup.cfg
