ccnmtl/django-pagetree

CHANGES.txt, setup.py
Releasing a new version since I'll need it for WORTH.
=> Version 1.0.4

pagetree/generic/views.py
See discussion here:
https://github.com/ccnmtl/ccnmtldjango/pull/45#discussion_r23717104
=> Allow anonymous access for non-gated pagetree sites

.travis.yml, pagetree/models.py, pagetree/templatetags/user_status.py, pagetree/tests/factories.py, pagetree/tests/test_models.py, pagetree/tests/test_templatetags.py, test_reqs.txt
For finding out whether each PageBlock on the Section is unlocked.
I'll need this for PMT #99684. You can see how I'm planning on using
this on the pageblock-gating branch of worth2:
https://github.com/ccnmtl/worth2/tree/pageblock-gating
=> Add Section.unlocked() method

pagetree/models.py
=> Fix duplicate IDs in pageblock modals

README.md
from: https://pypip.in/version.html
=> Add pypi link to readme

CHANGES.txt, pagetree/forms.py, pagetree/models.py, pagetree/views.py, test_reqs.txt
Treebeard 3.0 fixes some method deprecation warnings.
=> :arrow_up: django-treebeard 3.0 compatibility

pagetree/templates/delete_confirm.html, pagetree/views.py
=> Add confirmation page to pageblock delete button

CHANGES.txt, pagetree/media/css/pagetree.css, pagetree/templates/pagetree/edit_page.html, setup.py
Closes #66
Here's an example of what this looks like:
=> Add pageblock count to sections in the edit page

CHANGES.txt, pagetree/generic/views.py, pagetree/models.py, pagetree/templates/pagetree/clone_hierarchy.html, pagetree/templates/pagetree/edit_page.html, pagetree/tests/test_models.py, pagetree/urls.py, setup.py
full section copy with all pageblocks that support create_from_dict
=> Clone hierarchy view

README.md
so we have a better idea of when the docs are having problems
=> add docs badge to readme

README.md
https://github.com/badges/pypipins/issues/39
=> Remove pypi badge - pypin.in is down

CHANGES.txt, pagetree/models.py, setup.py
override to select the related hierarchy. this helps particularly with application menu rendering.
=> get_descendants optimization

.travis.yml, pagetree/forms.py, pagetree/generic/models.py, pagetree/generic/views.py, pagetree/helpers.py, pagetree/management/commands/pull_from_prod.py, pagetree/models.py, pagetree/reports.py, pagetree/templatetags/getroot.py, pagetree/templatetags/hasrelated.py, pagetree/templatetags/render.py, pagetree/templatetags/user_status.py, pagetree/test_models.py, pagetree/tests/factories.py, pagetree/tests/test_forms.py, pagetree/tests/test_generic.py, pagetree/tests/test_helpers.py, pagetree/tests/test_models.py, pagetree/tests/test_reports.py, pagetree/tests/test_templatetags.py, pagetree/tests/test_views.py, pagetree/tests/urls.py, pagetree/urls.py, pagetree/views.py, setup.py, test_reqs.txt
https://docs.djangoproject.com/en/1.9/topics/python3/
=> Add python 3.x compatibility

.gitignore, .jscsrc, .travis.yml, CHANGES.txt, Makefile, pagetree/forms.py, pagetree/static/pagetree/css/loading.css, pagetree/static/pagetree/js/src/clone-loading.js, pagetree/static/pagetree/js/src/pagetree-admin.js, pagetree/templates/pagetree/clone_hierarchy.html, pagetree/templates/pagetree/edit_page.html, pagetree/templates/pagetree/loading.html
Also adds jshint/jscs checks for pagetree's javascript
=> Add clone form loading animation - PMT #104950

pagetree/tests/factories.py, pagetree/tests/test_models.py
The RootSectionFactory was generating an invalid model.
=> Add factory tests

docs/conf.py
https://github.com/bitprophet/alabaster/issues/49#issuecomment-282850706
=> Add nicer documentation sidebar

pagetree/views.py
https://docs.djangoproject.com/en/1.10/topics/http/shortcuts/#render-to-response
=> Use render() instead of render_to_response()

.travis.yml
This combo shouldn't be excluded.
=> travis: test on python 3.5, django 2.2

.travis.yml
only test on LTS django releases.
=> travis: remove django 2.1 and 2.0 testing

.eslintrc.js, .github/workflows/build-and-test.yml, Makefile, js.mk, package-lock.json, package.json, runtests.py
* Update env to Ubuntu 20.04 and Python 3.8
* Update to django 3.2.13
* Replace jshint/jscs with eslint
* Add a package.json
=> Standardize make & build
